window.GRANITE_DENSITIES = [
  { id: "gabbro-diabaz", name: "Габбро-Диабаз", density: 3200 },
  { id: "kalguvaara", name: "Калгуваара", density: 2700 },
  { id: "dyadina-gora", name: "Дядина Гора", density: 2700 },
  { id: "onezhskiy-labradorit", name: "Онежский Лабрадорит", density: 2800 },
  { id: "vozrozhdenie", name: "Возрождение", density: 2700 },
  { id: "mavara", name: "Мавара", density: 3100 },
  { id: "dymovskiy", name: "Дымовский гранит", density: 2900 },
  { id: "kolskiy", name: "Кольский габбро-диорит", density: 2900 },
  { id: "onego-green", name: "Онего Грин", density: 2800 },
  { id: "vinga", name: "Винга", density: 2600 },
  { id: "hauki", name: "Хауки", density: 3200 },
  { id: "amphibolite", name: "Гранатовый амфиболит", density: 3000 },
  { id: "kupetskiy", name: "Купецкий гранит", density: 3000 },
  { id: "galaktika", name: "Галактика", density: 3100 },
  { id: "khibinite", name: "Хибинит", density: 2700 },
  { id: "krasnogorskiy", name: "Красногорский гранит", density: 2700 },
  { id: "sopka-buntina", name: "Сопка Бунтина", density: 2700 },
  { id: "kashina-gora", name: "Кашина Гора", density: 2600 }
];
