window.GRANITE_DENSITIES = [
  { id: "gabbro-diabaz", name: "Габбро-Диабаз", density: 3150 },
  { id: "kalguvaara", name: "Калгуваара", density: 2655 },
  { id: "dyadina-gora", name: "Дядина Гора", density: 2675 },
  { id: "onezhskiy-labradorit", name: "Онежский Лабрадорит", density: 2715 },
  { id: "vozrozhdenie", name: "Возрождение", density: 2675 },
  { id: "mavara", name: "Мавара", density: 2685 },
  { id: "dymovskiy", name: "Дымовский гранит", density: 2725 },
  { id: "kolskiy", name: "Кольский габбро-диорит", density: 2875 },
  { id: "onego-green", name: "Онего Грин", density: 3075 },
  { id: "vinga", name: "Винга", density: 2675 },
  { id: "hauki", name: "Хауки", density: 2975 },
  { id: "amphibolite", name: "Гранатовый амфиболит", density: 2760 },
  { id: "kupetskiy", name: "Купецкий гранит", density: 2685 },
  { id: "galaktika", name: "Галактика", density: 2900 },
  { id: "khibinite", name: "Хибинит", density: 2635 },
  { id: "krasnogorskiy", name: "Красногорский гранит", density: 2690 },
  { id: "sopka-buntina", name: "Сопка Бунтина", density: 3048 },
  { id: "kashina-gora", name: "Кашина Гора", density: 2665 }
];
